# Generated by Django 5.1 on 2024-08-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GDPdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region_name", models.TextField()),
                ("year", models.TextField()),
                ("value", models.FloatField(blank=True, null=True)),
                ("type", models.TextField()),
            ],
        ),
    ]
