# Generated by Django 5.1 on 2024-08-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gdpview", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NationalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField()),
                ("value", models.FloatField(blank=True, null=True)),
                ("year", models.TextField()),
            ],
        ),
    ]
